//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_chitietdiem
    {
        public int chitietdiemid { get; set; }
        public int diemid { get; set; }
        public Nullable<int> sodiem { get; set; }
        public string ghichu { get; set; }
    }
}
