//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_cauhoithuthach
    {
        public int cauhoiid { get; set; }
        public string noidung { get; set; }
        public string dapantext { get; set; }
        public string dapanABC { get; set; }
        public string ghichu { get; set; }
        public Nullable<int> cuocthiid { get; set; }
        public Nullable<int> vitri { get; set; }
    }
}
