//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_cuocthi
    {
        public int cuocthiid { get; set; }
        public string tencuocthi { get; set; }
        public Nullable<int> doi1id { get; set; }
        public Nullable<int> tongdiemdoi1 { get; set; }
        public Nullable<int> doi2id { get; set; }
        public Nullable<int> tongdiemdoi2 { get; set; }
        public Nullable<int> doi3id { get; set; }
        public Nullable<int> tongdiemdoi3 { get; set; }
        public Nullable<int> doi4id { get; set; }
        public Nullable<int> tongdiemdoi4 { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<System.DateTime> ngaytao { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<int> daxoa { get; set; }
        public string motacuocthi { get; set; }
    }
}
