//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_doi
    {
        public int doiid { get; set; }
        public string tendoi { get; set; }
        public string diachiip { get; set; }
        public string tennguoichoi { get; set; }
        public string tendangnhap { get; set; }
        public string matkhau { get; set; }
        public Nullable<int> vitridoi { get; set; }
        public string vaitro { get; set; }
        public Nullable<int> cuocthiid { get; set; }
    }
}
