//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_goicaudiscovery
    {
        public int cauhoiid { get; set; }
        public int doithiid { get; set; }
        public string chude { get; set; }
        public string noidungchude { get; set; }
        public string noidungthisinh { get; set; }
        public Nullable<int> vitri { get; set; }
        public Nullable<int> cauhoichaid { get; set; }
        public Nullable<int> cuocthiid { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<int> trangthailatAnhPhu { get; set; }
    }
}
