//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_hienthicautraloi
    {
        public int id { get; set; }
        public Nullable<int> cuocthiid { get; set; }
        public Nullable<int> doiid { get; set; }
        public Nullable<int> phanthiid { get; set; }
        public string cauhoi { get; set; }
        public string dapan { get; set; }
        public Nullable<bool> traloi { get; set; }
        public Nullable<int> cauhoiid { get; set; }
    }
}
