//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ds_userlogin
    {
        public int id { get; set; }
        public string tendoi { get; set; }
        public string tennguoichoi { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string role { get; set; }
        public Nullable<int> doiid { get; set; }
        public bool isreconnect { get; set; }
    }
}
