//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS_Project.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuaMienDiSanEntities : DbContext
    {
        public QuaMienDiSanEntities()
            : base("name=QuaMienDiSanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ds_cauhoithuthach> ds_cauhoithuthach { get; set; }
        public virtual DbSet<ds_cuocthi> ds_cuocthi { get; set; }
        public virtual DbSet<ds_chitietdiem> ds_chitietdiem { get; set; }
        public virtual DbSet<ds_diem> ds_diem { get; set; }
        public virtual DbSet<ds_doi> ds_doi { get; set; }
        public virtual DbSet<ds_goicaudiscovery> ds_goicaudiscovery { get; set; }
        public virtual DbSet<ds_goicauhoikhoidong> ds_goicauhoikhoidong { get; set; }
        public virtual DbSet<ds_goicauhoishining> ds_goicauhoishining { get; set; }
        public virtual DbSet<ds_hienthicautraloi> ds_hienthicautraloi { get; set; }
        public virtual DbSet<ds_phanthi> ds_phanthi { get; set; }
        public virtual DbSet<ds_phanthikhangia> ds_phanthikhangia { get; set; }
        public virtual DbSet<ds_userlogin> ds_userlogin { get; set; }
    }
}
